Fix error in watermarkImage when using text watermark
  Error: imagecreatefrompng(): Argument #1 ($filename) must be of type string, GdImage given

When using text watermaks, $this->watermarkImgPath is set to a GdImage
by watermarkCreateText().  We shouldn't then try to load it as a PNG.
Fix originally from @feeschwer:
  https://wordpress.org/support/topic/mehrere-anpassung-fur-php-8/